### ISSUE TITLE
Request for information on which allele was counted in the model

### ISSUE THREAD

**Issue by holgerman** [kevinVervier/SLINGER#1]
Hi Kevin,

thank you for sharing SLINGER code!
I tried to run SLINGER on my data, however, I did not found information which allele was counted in the model. 
Detailed, file https://github.com/kevinVervier/SLINGER/blob/master/model/AllSNPs-elasticNet.txt includes only columns gene, SNP, and beta, but a column informing on the counted allele code is missing.

Could you provide such information?
Thank you very much indeed,
Holger

**Comment by kevinVervier** [comment]
Hi Holger,

Thank you for your interest in using SLINGER.
I updated another model file with an additional column containing the allele we used for the count (see  	AllSNPs-elasticNet_withAllele.txt)

Best,
Kevin

**Comment by holgerman** [comment]
Hi Kevin,

thank you very much for the prompt answer and sorry for giving feedback from my side to your answer not earlier!
Following questions came:

First, in the new column, there are 3291 rows with no minor_allele code, e.g. rs17800281. Is this for a certain reason?

Second, I realized in rare cases that I do not have a corresponding allele in my dataset for a certain SNP *(e.g. rs1043099 T       vs G or  C). This is not unexpected, as my data likely relates to another dbSNP version. However, could you also provide the second allel - this would give the possibility to better filter out such problematic SNPs.

Thank you again!

Best Greetings, Holger
