### ISSUE TITLE
 Additional questions on information on which allele was counted in the model

### ISSUE THREAD

**Issue by holgerman** [kevinVervier/SLINGER#2]
Hi Kevin,

thank you very much for the prompt answer and sorry for giving feedback from my side to your answer not earlier!
Following questions came:

First, in the new column of AllSNPs-elasticNet_withAllele.txt, there are 3291 rows with no minor_allele code, e.g. rs17800281. Is this for a certain reason?

Second, I realized in rare cases that I do not have a corresponding allele in my dataset for a certain SNP *(e.g. rs1043099 T vs G or C). This is not unexpected, as my data likely relates to another dbSNP version. However, could you also provide the second allele - this would give the possibility to better filter out such problematic SNPs.

Thank you again!

Best Greetings, Holger

**Comment by kevinVervier** [comment]
Sorry about that. It seems that the dbSNP version as an impact on the annotation.
Actually, we followed the guidance provided in PrediXcan article: "Michigan Imputation Server with the following parameters: 1000G Phase 1 v3 ShapeIt2 (no singletons) reference panel, SHAPEIT phasing and the EUR (European) population. Non-ambiguous-stranded SNPs with MAF > 0.05 and imputation R2 > 0.8 were retained for subsequent analysis. "
If you follow those instructions, there should not be any dbSNP version issue. Let me know if it helps or not.
Thank you,
Kevin
